{{- /* Copyright 2026 The Protobuf Project authors.
       SPDX-License-Identifier: Apache-2.0 */ -}}
// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp {{ .Version }}
// source: {{ .SourcePath }}

#include "grpc_server.h"
#include "rust/mcp_include.h"

#include <chrono>
#include <cstdlib>
#include <iostream>
#include <string>
#include <thread>

static std::string env_or(const char* key, const char* fallback) {
    const char* val = std::getenv(key);
    return val ? val : fallback;
}

int main() {
    auto grpc_addr = env_or("GRPC_ADDR", "[::]:50051");
    auto transport = env_or("MCP_TRANSPORT", "http");

    {{ .CppNamespace }}::start_grpc_server(grpc_addr);
    std::this_thread::sleep_for(std::chrono::milliseconds(200));

    if (transport == "stdio") {
        std::cerr << "MCP attaching (transport=stdio)" << std::endl;
        {{ .CppNamespace }}::start_{{ .FirstServiceSnake }}_mcp_stdio();
    } else {
        auto host = env_or("MCP_HOST", "0.0.0.0");
        auto port_s = env_or("MCP_PORT", "8082");
        auto base = env_or("MCP_BASE_PATH", "{{ index .ServiceBasePaths .FirstServiceName }}");
        uint16_t port = static_cast<uint16_t>(std::stoi(port_s));
        std::cerr << "MCP attaching (transport=streamable-http, "
                  << host << ":" << port << base << ")" << std::endl;
        {{ .CppNamespace }}::start_{{ .FirstServiceSnake }}_mcp_http(host, port, base);
    }
    return 0;
}
