{{- /* Copyright 2026 The Protobuf Project authors.
       SPDX-License-Identifier: Apache-2.0 */ -}}
# Code generated by protoc-gen-mcp. DO NOT EDIT.
# versions: protoc-gen-mcp {{ .Version }}
# source: {{ .SourcePath }}
# Build: make (from cpp/) — binary outputs to cpp/server. This file delegates to cpp/.

.PHONY: all clean
all clean:
	$(MAKE) -C ../../../cpp $@
